config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'comments#new'
  get "comments/#{ENV['URL']}", to: 'comments#show'
  post '/comments/new', to: 'comments#create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :text, presence: true, length: {in: 1..50}
  validates :color, presence: true
  validates :size, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
# coding: utf-8
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.size = "60"
    @comment.color= "white"
    if @comment.save
      flash[:success] = "コメントを送信しました"
    else
      flash[:danger] = "コメントの送信に失敗しました"
    end
    redirect_to :action => "new"
  end
  
  def show
    if params["token"] === ENV["TOKEN"]
      @comment = Comment.where(is_used: false)
      @comment.each do |c|
        c.update_attribute(:is_used, true)
      end
      render :json => @comment
    end
  end

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/new.html.erb
<h1 class="title is-1 h1-title"> タクニコ動画 </h1>

<div class="form-field">
  <%= form_with :class=>"field", model: @comment, url: comments_new_path do |f| %>
  <%= f.label "コメント入力" , :class=>"comments-label" %>
  <%= f.text_field :text ,:class=>"comments-form" %>
  <%= f.submit "コメント送信" , :class=>"submit-button" %>
  <% end %>
</div>

app/views/comments/show.html.erb
<h1>Comments#show</h1>
<p>Find me in app/views/comments/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>タクニコ動画</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.2/css/bulma.min.css">
  </head>
  </head>

  <body>
    <% flash.each do |message_type,message| %>
      <% if message_type === "danger" %>
        <div class="<%= message_type %> notification is-danger"><%= message %> </div>
      <% elsif message_type === "success" %>
        <div class="<%= message_type %> notification is-primary"><%= message %> </div>
      <% end %>
    <% end %>
    <%= yield %>
  </body>
</html>